DROP TABLE IF EXISTS cards;

DROP TYPE IF EXISTS card_layout;

CREATE TYPE IF NOT EXISTS card_layout AS enum(
  'normal',
  'split',
  'double-faced',
  'token',
  'plane',
  'scheme',
  'phenomenon',
  'leveler',
  'vanguard',
  'aftermath'
  );

CREATE TABLE IF NOT EXISTS cards (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  mana_cost TEXT NOT NULL,
  cmc INTEGER NOT NULL,
  type TEXT NOT NULL,
  rarity TEXT NOT NULL,
  card_text TEXT,
  flavor_text TEXT,
  artist TEXT NOT NULL,
  creature_power TEXT,
  creature_toughness TEXT,
  planeswalker_loyalty TEXT,
  layout card_layout DEFAULT 'normal' NOT NULL,
  multiverse_id INTEGER NOT NULL,
  image_url TEXT NOT NULL,
  original_text TEXT NOT NULL,
  original_name TEXT NOT NULL,
  mtg_id TEXT NOT NULL
);